version: "3.9"

services:
  db:
    image: postgres:15
    container_name: booking_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: booking_redis
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data: